routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// User Routes
Route::group(['namespace' => 'User'], function(){
    Route::get('/', 'HomeController@index' )->name('index');
    
    /* I want to get the post via post slug */
    Route::get('post/{slug}', 'PostController@post' )->name('post');

    /* Get category posts via category slug */
    Route::get('post/category/{category}', 'HomeController@category')->name('category');

    /* Get tag posts via tag slug */
    Route::get('post/tag/{tag}', 'HomeController@tag')->name('tag');
    
    /* Vue Route */
    Route::post('getPosts', 'PostController@getAllPost');
    Route::post('saveLike', 'PostController@saveLike');

    
});


// Admin Routes
Route::group(['namespace' => 'Admin', 'middleware' => 'auth:admin'], function(){
    // Admin Home Route
    Route::get('admin/home', 'DashbController@index')->name('admin.home');    
    
    // Admin User Route
    Route::resource('admin/user', 'UserController');
    
    // Role Route
    Route::resource('admin/role', 'RoleController');
   
    // Permission Route
    Route::resource('admin/permission', 'PermissionController');
    
    // Admin Post Route
    Route::resource('admin/post', 'PostController');

    // Admin Category Route
    Route::resource('admin/category', 'CategoryController');

    // Admin Tag Route
    Route::resource('admin/tag', 'TagController');  

});

// Admin Auth Route
Route::get('admin-login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin-login', 'Admin\Auth\LoginController@login');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\admin\permission;
use Illuminate\Http\Request;

class PermissionController extends Controller
{

    public function __construct()
    {
        //$this->middleware('auth:admin');
        
        /* Easily you can use middleware for authorize actions*/
        $this->middleware('can:user-create');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = permission::all();
        return view('admin.permission.permission', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.permission.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:60|unique:permissions',
            'permission_for' => 'required',
        ]);
        $permission = new permission;
        $permission->name = $request->name;        
        $permission->permission_for = $request->permission_for;        
        $permission->save();
        return redirect(route('permission.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = permission::find($id);        
        return view('admin.permission.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:60|unique:permissions',
            'permission_for' => 'required',
        ]);
        $permission = permission::find($id);
        $permission->name = $request->name;    
        $permission->permission_for = $request->permission_for;    
        $permission->save();
        return redirect(route('permission.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = permission::find($id);
        $item->delete();
        session()->flash('message','Deleted Successfully');
        return redirect()->back();
    }
}

resources/views/admin/permission/create.blade.php
@extends('admin.layouts.app')

@section('main-content')

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add New Permission</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Home</a></li>
                        <li class="breadcrumb-item active">Permission</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-info">
                    <form action="{{route('permission.store')}}" method="post">

                        {{ csrf_field() }}

                        <div class="card-body">                            
                            <div class="col-md-4 offset-4">
                                <div class="form-group">
                                    <label for="name">Permission Name</label>
                                    <input type="text" class="form-control" name="name">
                                    @if ($errors->has('name'))                                            
                                        <p style="color:#ff0000; margin-top:5px;">{{ $errors->first('name') }}</p>
                                    @endif
                                </div>                               
                                <div class="form-group">
                                    <label for="name">Permission For</label>
                                    <select class="form-control" name="permission_for">
                                        <option selected disabled>Select Permision</option>
                                        <option value="user">User</option>
                                        <option value="post">Post</option>
                                        <option value="other">Other</option>
                                    </select>
                                    @if ($errors->has('permission_for'))                                            
                                        <p style="color:#ff0000; margin-top:5px;">{{ $errors->first('permission_for') }}</p>
                                    @endif
                                   
                                </div>                               
                                <div class="form-group">
                                    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{route('permission.index')}}" class="btn btn-secondary">Back</a>
                                </div>
                            </div>                            
                        </div>
                    </form>
                </div>
            </div>           
        </div>       
    </section>
</div>
@endsection

resources/views/admin/permission/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Update Permission</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Home</a></li>
                        <li class="breadcrumb-item active">Permission</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-info">
                    <form action="{{route('permission.update', $permission->id)}}" method="post">

                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="card-body">
                            <div class="col-md-4 offset-4">
                                <div class="form-group">
                                    <label for="name">Permission Name</label>
                                    <input type="text" class="form-control" name="name" value="{{$permission->name}}">
                                    @if ($errors->has('name'))
                                        <p style="color:#ff0000; margin-top:5px;">{{ $errors->first('name') }}</p>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="name">Permission For</label>
                                    <select class="form-control" name="permission_for">
                                        <option selected disabled>Select Permision</option>
                                        <option value="user" 
                                            @if ('user' == $permission->permission_for)
                                                {{'selected'}}
                                            @endif
                                            >User
                                        </option>
                                        <option value="post"
                                            @if ('post' == $permission->permission_for)
                                                {{'selected'}}
                                            @endif
                                            >Post
                                        </option>
                                        <option value="other"
                                            @if ('other' == $permission->permission_for)
                                                {{'selected'}}
                                            @endif
                                            >Other
                                        </option>
                                    </select>
                                    @if ($errors->has('permission_for'))                                            
                                        <p style="color:#ff0000; margin-top:5px;">{{ $errors->first('permission_for') }}</p>
                                    @endif
                                </div>          
                                <div class="form-group">
                                    <button type="submit" name="update" class="btn btn-primary">Update</button>
                                    <a href="{{route('permission.index')}}" class="btn btn-secondary">Back</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

resources/views/admin/permission/permission.blade.php
@extends('admin.layouts.app')

@section('headSection')
<link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">	
@endsection

@section('main-content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1>All Permissions</h1>
				</div>
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{route('admin.home')}}">Home</a></li>
						<li class="breadcrumb-item active">Permission</li>
					</ol>
				</div>
			</div>
		</div><!-- /.container-fluid -->
	</section>

	<!-- Main content -->
	<section class="content">

		<!-- Default box -->
		<div class="card">
			<div class="card-header">
				@include('admin.partial.message')
				<center><a href="{{route('permission.create')}}" class="btn btn-success">Add New Permission</a></center>
			</div>
			<div class="card-body">
				<table id="example1" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>SL No</th>
							<th>Permission Name</th>							
							<th>Permission For</th>							
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($permissions as $permission)
							<tr>
								<td>{{$loop->index + 1}}</td>								
								<td>{{$permission->name}}</td>								
								<td>{{$permission->permission_for}}</td>								
								<td><span><a class="btn btn-info" href="{{route('permission.edit', $permission->id)}}"><i class="far fa-edit"></i></a></span></td>
								<td>
									<form class="ml-2" action="{{route('permission.destroy', $permission->id)}}" method="post">
										{{csrf_field()}}
										{{method_field("DELETE")}}
										<span><button onclick="if(confirm('Are you sure, You want to delete this!')){}else{event.preventDefault();}" type="submit" name="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button></span>				    			
									</form>
								</td>
							</tr>
						@endforeach
						
					</tbody>
					<tfoot>
						<tr>
							<th>SL No</th>
							<th>Permission Name</th>
							<th>Permission For</th>							
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</tfoot>
				</table>
			</div>			
		</div>
		<!-- /.card -->

	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

@section('footerSection')
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script>
	$("#example1").DataTable({
		"responsive": true,
		"autoWidth": false,
	}); 
</script>
@endsection